src/App.tsx
src/components/RootingScreen/RootingScreen.tsx
src/components/RootingScreen/__snapshots__/RootingScreen.test.tsx.snap
src/components/SignInScreen/SignInScreen.tsx
src/pages/CasualBattle/Invitation/Invitation.test.tsx
src/pages/CasualBattle/Invitation/Invitation.tsx
src/pages/CasualBattle/Invitation/__snapshots__/Invitation.test.tsx.snap
src/pages/CasualBattle/Invitation/hooks/useInvitationState.test.ts
src/pages/CasualBattle/Invitation/hooks/useInvitationState.ts
src/pages/CasualBattle/WaitingRoom/WaitingRoom.test.tsx
src/pages/CasualBattle/WaitingRoom/WaitingRoom.tsx
src/pages/CasualBattle/WaitingRoom/__snapshots__/WaitingRoom.test.tsx.snap
src/pages/CasualBattle/WaitingRoom/hooks/useWaitingRoomState.test.ts
src/pages/CasualBattle/WaitingRoom/hooks/useWaitingRoomState.ts
src/services/RoomSync/RoomSync.test.ts
src/services/RoomSync/RoomSync.ts

ルームIDが含まれたURLをクリックするとルームに入ることができるルーム招待機能を実装した。
[仕様書](https://www.notion.so/ea4344dedbb444818cb1aad0f7b6b612?p=db37e217425b4a0ca94815fe977ff8d4)
やったこと
- Invitationページ並びにhooksの作成
- ルーティングの作成
- waiting-roomに招待リンクコピーボタンの作成
やってないこと
https://github.com/CodeParty2021/code_party_front/issues/30

ルームの招待機能の実装

---

src/pages/Start/components/FirebaseLoginForm/FirebaseLoginForm.tsx
src/pages/Start/components/FirebaseLoginForm/__snapshots__/FirebaseLoginForm.test.tsx.snap

ログイン後のエンドポイントが間違っていた。
エンドポイントを修正した。

ログイン後のリンクバグを修正

---

src/hooks/CodeAPIHooks/useCodeAPI.ts
src/pages/Code/Coding/hooks/useCodeHooks.tsx

testではResultAPIを使わないようになったので，フロントでもjsonIdを叩かないように修正
ローカルではバックエンドはfix-run-simlatorブランチで動作確認．フリーコーディングと対戦画面１人で正常動作

jsonIdを使わないように修正

---

src/pages/Code/Coding/Coding.test.tsx
src/pages/Code/Coding/Coding.tsx
src/pages/Code/Coding/hooks/useCodeHooks.test.tsx
src/pages/Code/Coding/hooks/useCodeHooks.tsx

コーディング画面にて、一度実行後、バツボタンでモーダルを閉じた後もう一度実行ボタンを押した際、jsonに変化がなかった場合においてのみUnityモーダルが描画されないバグが発生していた。
上のバグを修正した

再レンダリング画家からにバグを修正

---

src/pages/Event/SelectMode/SelectMode.test.tsx
src/pages/Event/SelectMode/SelectMode.tsx
src/pages/Event/SelectMode/SelectModeStyle.tsx
src/pages/Event/SelectMode/__snapshots__/SelectMode.test.tsx.snap
src/pages/Event/SelectMode/hooks/useSelectModeState.test.ts
src/pages/Event/SelectMode/hooks/useSelectModeState.ts

- [モード選択画面](http://localhost:3000/#/event/select-mode)ページのデザインアップデート
- Linkで遷移していたがbuttonhandlerで遷移するように書き換えた。

selectmodeページのデザイン完了

---

src/pages/Event/SelectAI/SelectAI.test.tsx
src/pages/Event/SelectAI/SelectAI.tsx
src/pages/Event/SelectAI/__snapshots__/SelectAI.test.tsx.snap
src/pages/Event/SelectAI/hooks/useSelectAIState.test.ts
src/pages/Event/SelectAI/hooks/useSelectAIState.ts

[AI選択画面](http://localhost:3000/#/event/select-ai)に戻るボタンの追加
それに付随したテスト類の更新

select ai画面に戻るボタンの追加

---

src/App.tsx
src/components/RootingScreen/RootingScreen.test.tsx
src/components/SignInScreen/SignInScreen.test.tsx
src/hooks/CodeAPIHooks/useFetchCodes.test.ts
src/hooks/RoomSyncHooks/useRoomSync.test.ts
src/pages/CasualBattle/Invitation/hooks/useInvitationState.test.ts
src/pages/CasualBattle/WaitingRoom/hooks/useWaitingRoomState.test.ts
src/pages/Code/CodeList/hooks/getCodesHooks.test.tsx
src/pages/Event/SelectAI/hooks/useSelectAIState.test.ts
src/services/RoomSync/DBListener/DBListener.test.ts
src/services/user/user.test.ts
src/services/user/user.ts
src/utils/PrivateRoute.test.tsx
src/utils/PrivateRoute.tsx
src/utils/__snapshots__/PrivateRoute.test.tsx.snap

/event/select-aiなどのログイン認証が必要とされるページでリロードすると/eventページもしくは/startページにリダイレクトされていた。
原因は再ログイン処理完了の前にPrivateRouteのログインチェックが走ってしまい、未ログイン判定となってしまっていた。
ログイン処理が完了するまではloading=trueとし、その間はloading画面を描画、loadingがfalseとなったときに、ログインチェックを行うことで、上の問題を解決した。

ページリロード時、トップページにリダイレクトされるのを防ぐ

---

src/pages/Code/Coding/hooks/useCodeHooks.tsx

MicroCMSのコンテンツが存在しないときエラーが表示されるようになっていた。
現状のコンテンツが見れなくなっていたので上の仕様をコメントアウトした。

[bugfix] microCMSのエラー処理をコメントアウト

---

docker-compose.yml
src/config.ts
src/firebase_config.ts

- ローカルで立ててあるFirebaseに接続するように変更
- フロントとバックエンドの環境変数を更新しているのでコピーし直してください
- [フロント](https://www.notion.so/Frontend-env-6c50632c787043b4a34d58680bf9a4fe)
- [バックエンド](https://www.notion.so/Backend-750a8dca400848d1a0ee8c8b1613d343)
- WebSocketが偶につながらなくなる
- databaseURLを設定したことで改善したと思われるが、根本的な原因は不明
- (更新) WebSocketでエラーが出たら、クッキー削除で治ります
- テスト環境はエミュレータに繋いでいない
- そもそもGithubからFirebaseにアクセスできないっぽい（エラーが出る）
- 現状はデータベースを更新する系のテストが無い

ローカルエミュレータを使用するように変更

---

.docker/Dockerfile.backend
.docker/Dockerfile.firebase
.docker/Dockerfile.frontend
README.md
docker-compose.yml

- Dockerでホットリロードがかかるように修正
- docker-compose.ymlの環境変数に`WATCHPACK_POLLING=true`を設定
- コンテナ名を付けました
- フロントエンド：code_party_frontend
- Storybook：code_party_storybook
- バックエンド：code_party_backend
- Firebase：code_party_firebase
- Dockerを軽量化
- `yarn`タイミングをビルド時に変更
- `docker-compose start`毎に`yarn`するのは重くてストレス
- パッケージ更新時は`docker-compose build`をする必要あり
- `code_party_storybook`のnode_modulesを`code_party_frontend`のnode_modulesと共通化
- Volumeサイズが１つ1.3GBぐらいあった＋同じ内容、だったので共通化
- buildは１つずつ走るけど、同時にbuildが走るとyarnがロックするかもしれん
- 特に無し！

フロントエンドのDockerの修正

---

src/components/DescriptionPanel/components/CMSRender/CMSRenderer.tsx

keyががないことでwarningが出ていたので修正。
仮想DOMの更新時に参照するためのkeyらしいので今回はバグにはつながらない気がするが、見た目が悪いので修正した。

Wariningの修正

---

src/pages/Code/Coding/Coding.test.tsx
src/pages/Code/Coding/Coding.tsx
src/pages/Code/Coding/__snapshots__/Coding.test.tsx.snap
src/pages/Code/Coding/hooks/useCodeHooks.tsx

- [お助けメソッドタブの追加](https://www.notion.so/b56b9c9bac0d4a53b4cdd7934dca1531)
- コーディング画面にHELPタブを作って[Notion](https://four-forest-c7b.notion.site/4cb8096d110c47e19891d2df8a445122)へリンクした。

お助け関数説明ページへのリンク追加

---

src/hooks/RoomSyncHooks/useRoomSync.ts
src/services/RoomSync/DBListener/DBListener.test.ts
src/services/RoomSync/DBListener/DBListener.ts
src/services/RoomSync/DBOperator/DBOperator.test.ts
src/services/RoomSync/DBOperator/DBOperator.ts
src/services/RoomSync/RoomSync.ts
src/styles/constants/constants.ts
src/utils/Base32.test.tsx
src/utils/Base32.tsx

- [URLの短縮](https://www.notion.so/URL-2aaa310bd7124dcbb21e857b6c58291f)
- Base32を実装
- Base32を用いた任意長IDの生成関数
- Base32へのエンコード関数
- Base32の仕様はこちらを参照
- [Base32](http://www.crockford.com/base32.html)
- ルームIDをID長4文字のBase32IDに短縮
- 例：P4SD、1AB3など
- 一応、ルームIDの重複チェックをしています
- 32^4種類作れるので、100万ほどの同時接続に耐えれます
- ただし、ルームは全員が正しく退室しない場合は残るので、ルームを整理する定期ジョブが必要になる可能性があります。
- Base32は人が読みやすいIDを目的とした文字セットです。
- 例
- 記号は含まない英数字のみのIDです。
- `i`や`l`は1に、`o`は0にエンコードされます。
- `u`は暴力的な英単語に含まれやすいので文字セットから外されています。

ルームIDをBase32を使用した４文字IDに短縮

---

src/components/PlayerPlate/Me/PlayerPlateMeStyle.tsx
src/components/PlayerPlate/Me/__snapshots__/PlayerPlateMe.test.tsx.snap
src/components/PlayerPlate/Other/PlayerPlateOtherStyle.tsx
src/components/PlayerPlate/Other/__snapshots__/PlayerPlateOther.test.tsx.snap
src/pages/RoomMatch/WaitingRoom/WaitingRoom.tsx
src/pages/RoomMatch/WaitingRoom/__snapshots__/WaitingRoom.test.tsx.snap
src/services/RoomSync/DBOperator/DBOperator.test.ts
src/services/RoomSync/DBOperator/DBOperator.ts
src/services/RoomSync/RoomSync.ts
src/utils/RemoveUndefinedFromObject.ts

- プレイヤープレートで名前が長すぎると枠を飛び出るバグを修正
- 飛び出る場合は...で省略するように修正
- 待機画面のユーザアイコンを表示するように修正
- アイコンはfirebaseのrealtime dbで共有するように実装
- プレイヤープレートの表示例
- 待機画面の表示例
- 左から、アイコンあり、アイコンあり、アイコンなし、アイコン画像が無効なURL

プレイヤープレートの表示の修正、待機画面のユーザアイコンの修正

---

src/hooks/RoomSyncHooks/useRoomSync.ts
src/pages/RoomMatch/Lobby/hooks/useLobbyState.ts
src/services/RoomSync/DBOperator/DBOperator.ts

- [フレンド対戦モードで５人以上入ることができるバグを修正](https://www.notion.so/053781ed048b4d4e96d4e649726b2078)
- ルーム入室処理の前に、ルーム内のメンバー数のチェック処理を追加
- メンバー数が4人未満の場合のみ、入室処理を実行
- メンバー数が既に4人の場合は、エラーメッセージを表示
- 5人以上入ろうとしても入室できない && エラーメッセージが表示される

フレンド対戦モードで５人以上入ることができるバグを修正

---

src/pages/Code/Coding/hooks/useCodeHooks.tsx

https://www.notion.so/c2ed054bced64076acebfda5bd645b6e
- フリーコーディングのボタンを連打したときに、イベントハンドラを1回のみ実行するように修正

実行ボタンを連打できる問題を修正

---

src/components/Avatar/AvatarStyle.tsx
src/components/Button/Button.stories.tsx
src/components/Button/Button.test.tsx
src/components/Button/ButtonStyle.tsx
src/pages/Code/Coding/Coding.test.tsx
src/pages/Code/Coding/Coding.tsx
src/pages/Code/Coding/__snapshots__/Coding.test.tsx.snap
src/pages/Code/Coding/hooks/useCodeHooks.tsx
src/pages/RoomMatch/WaitingRoom/WaitingRoom.test.tsx
src/pages/RoomMatch/WaitingRoom/WaitingRoom.tsx
src/pages/RoomMatch/WaitingRoom/components/CodeSelect.tsx
src/pages/RoomMatch/WaitingRoom/components/CodeSelectStyle.tsx
src/pages/RoomMatch/WaitingRoom/hooks/useWaitingRoomState.test.ts
src/pages/RoomMatch/WaitingRoom/hooks/useWaitingRoomState.ts

- [フリーコーディング（ルーム対戦）デザイン実装](https://www.notion.so/a1751d83a98843648a43556cd8fbb8c9?pvs=4)
- [コード選択モーダルからフリーコーディングに飛べる機能を実装](https://github.com/CodeParty2021/code_party_front/commit/b21bc61bc9297a7d38096268fda7c5773d5221ac)
- コード選択モーダルからフリーコーディングに「へんしゅう」ボタンから飛べる
- 戻るとモーダルが開いた状態になっている
- 部屋にも入った状態
- スクショ
- [ボタンのサイズを追加](https://github.com/CodeParty2021/code_party_front/commit/4d7d582a6884e9145ee110cb6262d389bf14080f)
- M2サイズを追加
- [Avatarのデザインを修正](https://github.com/CodeParty2021/code_party_front/commit/02ce2fb653342968ff742557affff16e8a057b13)
- おそらく #128 での修正漏れ

フリーコーディング（ルーム対戦）デザイン実装

---

src/pages/RoomMatch/WaitingRoom/components/CodeSelectStyle.tsx

コードが増えると対戦画面のコード選択がつぶれる問題。
flexやめるかmin-heightをつけるかの二択でflex残しました。

[対戦画面]min-heightを追加

---

src/hooks/CodeAPIHooks/errors.ts
src/hooks/CodeAPIHooks/useCodeAPI.ts
src/hooks/CodeAPIHooks/useRunCodes.ts
src/hooks/ResultHooks/useResult.ts
src/pages/Code/Coding/Coding.test.tsx
src/pages/Code/Coding/Coding.tsx
src/pages/Code/Coding/__snapshots__/Coding.test.tsx.snap
src/pages/Code/Coding/components/LogError/LogError.stories.tsx
src/pages/Code/Coding/components/LogError/LogError.test.tsx
src/pages/Code/Coding/components/LogError/LogError.tsx
src/pages/Code/Coding/components/LogError/LogErrorStyle.tsx
src/pages/Code/Coding/components/LogError/__snapshots__/LogError.test.tsx.snap
src/pages/Code/Coding/hooks/useCodeHooks.tsx

- [コンパイルエラーをログに表示する](https://www.notion.so/44ac3567803445ff9bebd0d83df6fede?pvs=4)
- やることが全く同じなので、下記のPRに続けて編集を加えています 🙏 
- #138 
- select関数未定義の場合
- 構文エラーが起きた場合
- フックのテストなどは工数が膨らむのでやっていません
- コーディングページにて、select関数が無い場合にエラーが発生し、ログパネルにエラー内容が表示されること
- コーディングページにて、構文エラーがある場合にエラーが発生し、ログパネルにエラー内容が表示されること
- 構文エラーの行数が一致していること

コンパイルエラーをログに表示する

---

src/hooks/CodeAPIHooks/useCodeAPI.ts
src/hooks/ResultHooks/useResult.ts
src/pages/Code/Coding/Coding.test.tsx
src/pages/Code/Coding/Coding.tsx
src/pages/Code/Coding/__snapshots__/Coding.test.tsx.snap
src/pages/Code/Coding/hooks/useCodeHooks.tsx

急いでSSしたのでフォント読み込まれてないけど
生レスポンスは不要な情報を大量に含むので最上部の必要なところだけ表示
検索部分の実装が急ぎすぎて負債

エラーメッセージをログに表示
